# generated-from:e09dee96ebf4666ccbcec622d28d1772a2c1f53310b3395b4114a1fce494a91f DO NOT REMOVE, DO UPDATE

ACHTestHarness:
  Servers:
    FTP:
      RootPath: "./storage/ftp/"
      Hostname: "localhost"
      Port: 2222
      Auth:
        Username: "admin"
        Password: "secret"
      PassivePorts: "30000-30009"
      Paths:
        # Incoming Files
        Files: "" # Path to look for uploaded files
        # Outgoing Files
        Bar: "" # TODO(adam):
    Admin:
      Bind:
        Address: ":3333"
  Responses:
    - match:
        traceNumber: "123456789012345"
      action:
        return:
          code: "R03"
    - match:
        debit:
        amount:
          min: 100000 # $1,000
          # "max <number>" # optional value
      action:
        return:
          code: "R01"
    - match:
        accountNumber: "987654321"
        amount:
          value: 45121 # $451.21
      action:
        return:
          code: "R01"
    - match:
        accountNumber: "333333"
      action:
        correction:
          code: "C01"
          data: "444444"
